name: Coveralls

on:
  workflow_call:

jobs:
  tests:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout branch
        uses: actions/checkout@v3
      - name: Use Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18.10.0'
      - name: Install dependencies
        run: yarn --immutable
      - name: Run Test Coverage
        run: yarn test:coverage
      - name: Coveralls
        uses: coverallsapp/github-action@master
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
